### ISSUE TITLE
Integrate speech.js with webview on sample app

### ISSUE THREAD

**Issue by adamaji** [carolina-tech-explorers/live-captioning#5]
@clairehslin 

Look into adding the speech.js demo into the sample webview app

**Comment by adamaji** [comment]
Stuff to add to the webview page:
1) tap to start button
2) speech text displayed

---

Other things to think about:
1) run while off
2) connect to play/pause

**Comment by bhwarren** [comment]
the webview will not support webspeech api anytime soon (see comment on issue #3). This will only work on mobile Chrome, and therefore we'd need a backend and a lot of network communication to make it work
