### ISSUE TITLE
Try integrating Bo's solution as Cordova plugin

### ISSUE THREAD

**Issue by adamaji** [carolina-tech-explorers/live-captioning#7]
Developing the plugin to interface between cordova and the native solution

**Comment by bhwarren** [comment]
check logcat for the results, nothing will appear on the screen.  click the mail button to start

**Comment by bhwarren** [comment]
Also it will quit if it can't find any results for either speech or silence

**Comment by adamaji** [comment]
Using these 
https://github.com/poiuytrez/SpeechRecognizer
https://github.com/daao87/ContinuousSpeechRecognizer
as reference

**Comment by adamaji** [comment]
https://cordova.apache.org/docs/en/4.0.0/guide/hybrid/plugins/

and, made a new repo at carolina-glass-explorers/continuous-speech-recognizer-plugin

**Comment by adamaji** [comment]
https://cordova.apache.org/docs/en/4.0.0/guide/platforms/android/plugin.html
or 
https://cordova.apache.org/docs/en/2.9.0/guide/plugin-development/android/
depending on version
